// <auto-generated />
using System;
using System.Collections.Generic;
using Booking.Domain.Models.BookingRequests;
using Booking.Domain.Models.InstituteCoordinators;
using Booking.Domain.Propagated.BookingRequests;
using Booking.Infrastructure.EFCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Booking.Infrastructure.Migrations
{
    [DbContext(typeof(BookingDbContext))]
    partial class BookingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "booking_frequency", new[] { "everyday", "undefined", "weekly" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "booking_schedule_status", new[] { "booked", "booking_approved", "booking_cancel_error", "booking_cancelled", "not_sent" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "booking_status", new[] { "approved_by_moderator", "error", "event_finished", "new", "rejected_by_moderator", "rejected_in_edms", "sent_for_approval_in_edms", "sent_for_moderation" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Booking.Domain.Events.BookingEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BookingRequestId")
                        .HasColumnType("integer")
                        .HasColumnName("booking_request_id");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.HasKey("Id")
                        .HasName("pk_booking_events");

                    b.HasIndex("BookingRequestId")
                        .HasDatabaseName("ix_booking_events_booking_request_id");

                    b.ToTable("booking_events", (string)null);
                });

            modelBuilder.Entity("Booking.Domain.Models.BookingRequests.BookingRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<IEnumerable<BookingTime>>("BookingSchedule")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("booking_schedule");

                    b.Property<BookingScheduleStatus?>("BookingScheduleStatus")
                        .HasColumnType("booking_schedule_status")
                        .HasColumnName("booking_schedule_status");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("EventHostFullName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("event_host_full_name");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("event_name");

                    b.Property<string>("ModeratorComment")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("moderator_comment");

                    b.Property<int>("ParticipantsCount")
                        .HasColumnType("integer")
                        .HasColumnName("participants_count");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<string>("RoomEventCoordinator")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("room_event_coordinator");

                    b.PrimitiveCollection<int[]>("RoomIds")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("room_ids");

                    b.Property<BookingStatus>("Status")
                        .HasColumnType("booking_status")
                        .HasColumnName("status");

                    b.Property<bool>("TechEmployeeRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("tech_employee_required");

                    b.HasKey("Id")
                        .HasName("pk_booking_requests");

                    b.ToTable("booking_requests", (string)null);
                });

            modelBuilder.Entity("Booking.Domain.Models.InstituteCoordinators.InstituteCoordinator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Institute")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("institute");

                    b.Property<List<Coordinator>>("coordinators")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("coordinators");

                    b.HasKey("Id")
                        .HasName("pk_institute_coordinators");

                    b.ToTable("institute_coordinators", (string)null);
                });

            modelBuilder.Entity("Booking.Domain.Events.BookingEvent", b =>
                {
                    b.HasOne("Booking.Domain.Models.BookingRequests.BookingRequest", null)
                        .WithMany()
                        .HasForeignKey("BookingRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_booking_events_booking_requests_booking_request_id");
                });

            modelBuilder.Entity("Booking.Domain.Models.BookingRequests.BookingRequest", b =>
                {
                    b.OwnsOne("Booking.Domain.Models.BookingRequests.BookingCreator", "Creator", b1 =>
                        {
                            b1.Property<int>("BookingRequestId")
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("creator_email");

                            b1.Property<string>("FullName")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("creator_full_name");

                            b1.Property<string>("PhoneNumber")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("creator_phone_number");

                            b1.HasKey("BookingRequestId");

                            b1.ToTable("booking_requests");

                            b1.WithOwner()
                                .HasForeignKey("BookingRequestId")
                                .HasConstraintName("fk_booking_requests_booking_requests_id");
                        });

                    b.Navigation("Creator")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
