// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Rooms.Domain.Models.BookingRequests;
using Rooms.Domain.Models.Equipments;
using Rooms.Domain.Models.Room;
using Rooms.Domain.Models.Room.Fix;
using Rooms.Domain.Models.Room.Parameters;
using Rooms.Infrastructure;

#nullable disable

namespace Rooms.Infrastructure.Migrations
{
    [DbContext(typeof(RoomsDbContext))]
    [Migration("20251117193831_BookingRequest")]
    partial class BookingRequest
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "room_layout", new[] { "amphitheater", "flat", "unspecified" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "room_net_type", new[] { "none", "unspecified", "wired", "wired_and_wireless", "wireless" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "room_status", new[] { "not_ready", "partially_ready", "ready", "unspecified" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "room_type", new[] { "computer", "mixed", "multimedia", "special", "unspecified" });
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "hstore");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Rooms.Domain.Models.BookingRequests.BookingRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<IEnumerable<BookingTime>>("BookingSchedule")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("booking_schedule");

                    b.Property<int?>("BookingScheduleStatus")
                        .HasColumnType("integer")
                        .HasColumnName("booking_schedule_status");

                    b.Property<string>("CoordinatorFullName")
                        .HasColumnType("text")
                        .HasColumnName("coordinator_full_name");

                    b.Property<string>("CoordinatorInstitute")
                        .HasColumnType("text")
                        .HasColumnName("coordinator_institute");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("EventHostFullName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("event_host_full_name");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("event_name");

                    b.Property<int>("EventType")
                        .HasColumnType("integer")
                        .HasColumnName("event_type");

                    b.Property<string>("ModeratorComment")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("moderator_comment");

                    b.Property<int>("ParticipantsCount")
                        .HasColumnType("integer")
                        .HasColumnName("participants_count");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<bool>("TechEmployeeRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("tech_employee_required");

                    b.HasKey("Id")
                        .HasName("pk_booking_requests");

                    b.ToTable("booking_requests", (string)null);
                });

            modelBuilder.Entity("Rooms.Domain.Models.Equipments.Equipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("comment");

                    b.Property<string>("InventoryNumber")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("inventory_number");

                    b.Property<string>("NetworkEquipmentIp")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("network_equipment_ip");

                    b.Property<int>("RoomId")
                        .HasColumnType("integer")
                        .HasColumnName("room_id");

                    b.Property<int>("SchemaId")
                        .HasColumnType("integer")
                        .HasColumnName("schema_id");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("serial_number");

                    b.Property<int?>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_equipments");

                    b.HasIndex("RoomId")
                        .HasDatabaseName("ix_equipments_room_id");

                    b.HasIndex("SchemaId")
                        .HasDatabaseName("ix_equipments_schema_id");

                    b.ToTable("equipments", (string)null);
                });

            modelBuilder.Entity("Rooms.Domain.Models.Equipments.EquipmentSchema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<Dictionary<string, string>>("ParameterValues")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("parameter_values");

                    b.Property<int>("TypeId")
                        .HasColumnType("integer")
                        .HasColumnName("type_id");

                    b.HasKey("Id")
                        .HasName("pk_equipment_schemas");

                    b.HasIndex("TypeId")
                        .HasDatabaseName("ix_equipment_schemas_type_id");

                    b.ToTable("equipment_schemas", (string)null);
                });

            modelBuilder.Entity("Rooms.Domain.Models.Equipments.EquipmentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<List<EquipmentParameterDescriptor>>("Parameters")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("parameters");

                    b.HasKey("Id")
                        .HasName("pk_equipment_types");

                    b.ToTable("equipment_types", (string)null);
                });

            modelBuilder.Entity("Rooms.Domain.Models.InstituteResponsible.InstituteResponsible", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Institute")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("institute");

                    b.Property<Dictionary<string, string>>("Responsible")
                        .IsRequired()
                        .HasColumnType("hstore")
                        .HasColumnName("responsible");

                    b.HasKey("Id")
                        .HasName("pk_institute_responsible");

                    b.ToTable("institute_responsible", (string)null);
                });

            modelBuilder.Entity("Rooms.Domain.Models.OperatorDepartments.OperatorDepartment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Contacts")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("contacts");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<Dictionary<string, string>>("Operators")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("operators");

                    b.HasKey("Id")
                        .HasName("pk_operator_departments");

                    b.ToTable("operator_departments", (string)null);
                });

            modelBuilder.Entity("Rooms.Domain.Models.Room.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AllowBooking")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_booking");

                    b.Property<RoomAttachments>("Attachments")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("attachments");

                    b.Property<int?>("BookingRequestId")
                        .HasColumnType("integer")
                        .HasColumnName("booking_request_id");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.Property<int?>("OperatorDepartmentId")
                        .HasColumnType("integer")
                        .HasColumnName("operator_department_id");

                    b.Property<string>("Owner")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("owner");

                    b.HasKey("Id")
                        .HasName("pk_rooms");

                    b.HasIndex("BookingRequestId")
                        .HasDatabaseName("ix_rooms_booking_request_id");

                    b.HasIndex("OperatorDepartmentId")
                        .HasDatabaseName("ix_rooms_operator_department_id");

                    b.ToTable("rooms", (string)null);
                });

            modelBuilder.Entity("Rooms.Domain.Models.BookingRequests.BookingRequest", b =>
                {
                    b.OwnsOne("Rooms.Domain.Models.BookingRequests.BookingCreator", "Creator", b1 =>
                        {
                            b1.Property<int>("BookingRequestId")
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("creator_email");

                            b1.Property<string>("FullName")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("creator_full_name");

                            b1.Property<string>("PhoneNumber")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("creator_phone_number");

                            b1.HasKey("BookingRequestId");

                            b1.ToTable("booking_requests");

                            b1.WithOwner()
                                .HasForeignKey("BookingRequestId")
                                .HasConstraintName("fk_booking_requests_booking_requests_id");
                        });

                    b.Navigation("Creator")
                        .IsRequired();
                });

            modelBuilder.Entity("Rooms.Domain.Models.Equipments.Equipment", b =>
                {
                    b.HasOne("Rooms.Domain.Models.Room.Room", null)
                        .WithMany("equipments")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_equipments_rooms_room_id");

                    b.HasOne("Rooms.Domain.Models.Equipments.EquipmentSchema", "Schema")
                        .WithMany()
                        .HasForeignKey("SchemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_equipments_equipment_schemas_schema_id");

                    b.Navigation("Schema");
                });

            modelBuilder.Entity("Rooms.Domain.Models.Equipments.EquipmentSchema", b =>
                {
                    b.HasOne("Rooms.Domain.Models.Equipments.EquipmentType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_equipment_schemas_equipment_types_type_id");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Rooms.Domain.Models.Room.Room", b =>
                {
                    b.HasOne("Rooms.Domain.Models.BookingRequests.BookingRequest", null)
                        .WithMany("rooms")
                        .HasForeignKey("BookingRequestId")
                        .HasConstraintName("fk_rooms_booking_requests_booking_request_id");

                    b.HasOne("Rooms.Domain.Models.OperatorDepartments.OperatorDepartment", null)
                        .WithMany("Rooms")
                        .HasForeignKey("OperatorDepartmentId")
                        .HasConstraintName("fk_rooms_operator_departments_operator_department_id");

                    b.OwnsOne("Rooms.Domain.Models.Room.Fix.RoomFixInfo", "FixInfo", b1 =>
                        {
                            b1.Property<int>("RoomId")
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            b1.Property<string>("Comment")
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("fix_info_comment");

                            b1.Property<DateTime?>("FixDeadline")
                                .HasColumnType("timestamptz")
                                .HasColumnName("fix_info_fix_deadline");

                            b1.Property<RoomStatus>("Status")
                                .HasColumnType("room_status")
                                .HasColumnName("fix_info_status");

                            b1.HasKey("RoomId");

                            b1.ToTable("rooms");

                            b1.WithOwner()
                                .HasForeignKey("RoomId")
                                .HasConstraintName("fk_rooms_rooms_id");
                        });

                    b.OwnsOne("Rooms.Domain.Models.Room.Parameters.RoomParameters", "Parameters", b1 =>
                        {
                            b1.Property<int>("RoomId")
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            b1.Property<int?>("ComputerSeats")
                                .HasColumnType("integer")
                                .HasColumnName("parameters_computer_seats");

                            b1.Property<bool?>("HasConditioning")
                                .HasColumnType("boolean")
                                .HasColumnName("parameters_has_conditioning");

                            b1.Property<RoomLayout>("Layout")
                                .HasColumnType("room_layout")
                                .HasColumnName("parameters_layout");

                            b1.Property<RoomNetType>("NetType")
                                .HasColumnType("room_net_type")
                                .HasColumnName("parameters_net_type");

                            b1.Property<int?>("Seats")
                                .HasColumnType("integer")
                                .HasColumnName("parameters_seats");

                            b1.Property<RoomType>("Type")
                                .HasColumnType("room_type")
                                .HasColumnName("parameters_type");

                            b1.HasKey("RoomId");

                            b1.ToTable("rooms");

                            b1.WithOwner()
                                .HasForeignKey("RoomId")
                                .HasConstraintName("fk_rooms_rooms_id");
                        });

                    b.OwnsOne("Rooms.Domain.Models.Room.RoomScheduleAddress", "ScheduleAddress", b1 =>
                        {
                            b1.Property<int>("RoomId")
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            b1.Property<string>("Address")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("schedule_address_address");

                            b1.Property<string>("RoomNumber")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("schedule_address_room_number");

                            b1.HasKey("RoomId");

                            b1.ToTable("rooms");

                            b1.WithOwner()
                                .HasForeignKey("RoomId")
                                .HasConstraintName("fk_rooms_rooms_id");
                        });

                    b.Navigation("FixInfo")
                        .IsRequired();

                    b.Navigation("Parameters")
                        .IsRequired();

                    b.Navigation("ScheduleAddress");
                });

            modelBuilder.Entity("Rooms.Domain.Models.BookingRequests.BookingRequest", b =>
                {
                    b.Navigation("rooms");
                });

            modelBuilder.Entity("Rooms.Domain.Models.OperatorDepartments.OperatorDepartment", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("Rooms.Domain.Models.Room.Room", b =>
                {
                    b.Navigation("equipments");
                });
#pragma warning restore 612, 618
        }
    }
}
