// <auto-generated />
using System;
using Domain.Models.Room.Fix;
using Domain.Models.Room.Parameters;
using Domain.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Domain.Migrations
{
    [DbContext(typeof(DomainDbContext))]
    partial class DomainDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "room_layout", new[] { "amphitheater", "flat", "unspecified" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "room_net_type", new[] { "none", "unspecified", "wired", "wired_and_wireless", "wireless" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "room_status", new[] { "not_ready", "partially_ready", "ready", "unknown" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "room_type", new[] { "computer", "mixed", "multimedia", "special", "unspecified" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Models.Room.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AllowBooking")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_booking");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.Property<string>("Owner")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("owner");

                    b.HasKey("Id")
                        .HasName("pk_rooms");

                    b.ToTable("rooms", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Room.Room", b =>
                {
                    b.OwnsOne("Domain.Models.Room.Fix.RoomFixInfo", "FixInfo", b1 =>
                        {
                            b1.Property<int>("RoomId")
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            b1.Property<string>("Comment")
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("fix_info_comment");

                            b1.Property<DateTime?>("FixDeadline")
                                .HasColumnType("timestamptz")
                                .HasColumnName("fix_info_fix_deadline");

                            b1.Property<RoomStatus>("Status")
                                .HasColumnType("room_status")
                                .HasColumnName("fix_info_status");

                            b1.HasKey("RoomId");

                            b1.ToTable("rooms");

                            b1.WithOwner()
                                .HasForeignKey("RoomId")
                                .HasConstraintName("fk_rooms_rooms_id");
                        });

                    b.OwnsOne("Domain.Models.Room.Parameters.RoomParameters", "Parameters", b1 =>
                        {
                            b1.Property<int>("RoomId")
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            b1.Property<int?>("ComputerSeats")
                                .HasColumnType("integer")
                                .HasColumnName("parameters_computer_seats");

                            b1.Property<bool?>("HasConditioning")
                                .HasColumnType("boolean")
                                .HasColumnName("parameters_has_conditioning");

                            b1.Property<RoomLayout>("Layout")
                                .HasColumnType("room_layout")
                                .HasColumnName("parameters_layout");

                            b1.Property<RoomNetType>("NetType")
                                .HasColumnType("room_net_type")
                                .HasColumnName("parameters_net_type");

                            b1.Property<int?>("Seats")
                                .HasColumnType("integer")
                                .HasColumnName("parameters_seats");

                            b1.Property<RoomType>("Type")
                                .HasColumnType("room_type")
                                .HasColumnName("parameters_type");

                            b1.HasKey("RoomId");

                            b1.ToTable("rooms");

                            b1.WithOwner()
                                .HasForeignKey("RoomId")
                                .HasConstraintName("fk_rooms_rooms_id");
                        });

                    b.OwnsOne("Domain.Models.Room.RoomAttachments", "Attachments", b1 =>
                        {
                            b1.Property<int>("RoomId")
                                .HasColumnType("integer");

                            b1.HasKey("RoomId");

                            b1.ToTable("rooms");

                            b1
                                .ToJson("attachments")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("RoomId")
                                .HasConstraintName("fk_rooms_rooms_room_id");

                            b1.OwnsOne("Domain.Models.File", "PdfRoomScheme", b2 =>
                                {
                                    b2.Property<int>("RoomAttachmentsRoomId")
                                        .HasColumnType("integer");

                                    b2.Property<string>("Filename")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.HasKey("RoomAttachmentsRoomId")
                                        .HasName("pk_rooms");

                                    b2.ToTable("rooms");

                                    b2.ToJson("attachments");

                                    b2.WithOwner()
                                        .HasForeignKey("RoomAttachmentsRoomId")
                                        .HasConstraintName("fk_rooms_rooms_room_attachments_room_id");

                                    b2.OwnsOne("Domain.Models.Location", "Location", b3 =>
                                        {
                                            b3.Property<int>("FileRoomAttachmentsRoomId")
                                                .HasColumnType("integer");

                                            b3.Property<string>("Bucket")
                                                .IsRequired()
                                                .HasColumnType("text");

                                            b3.Property<Guid>("Id")
                                                .HasColumnType("uuid");

                                            b3.HasKey("FileRoomAttachmentsRoomId")
                                                .HasName("pk_rooms");

                                            b3.ToTable("rooms");

                                            b3.ToJson("attachments");

                                            b3.WithOwner()
                                                .HasForeignKey("FileRoomAttachmentsRoomId")
                                                .HasConstraintName("fk_rooms_rooms_file_room_attachments_room_id");
                                        });

                                    b2.Navigation("Location")
                                        .IsRequired();
                                });

                            b1.OwnsOne("Domain.Models.File", "Photo", b2 =>
                                {
                                    b2.Property<int>("RoomAttachmentsRoomId")
                                        .HasColumnType("integer");

                                    b2.Property<string>("Filename")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.HasKey("RoomAttachmentsRoomId")
                                        .HasName("pk_rooms");

                                    b2.ToTable("rooms");

                                    b2.ToJson("attachments");

                                    b2.WithOwner()
                                        .HasForeignKey("RoomAttachmentsRoomId")
                                        .HasConstraintName("fk_rooms_rooms_room_attachments_room_id");

                                    b2.OwnsOne("Domain.Models.Location", "Location", b3 =>
                                        {
                                            b3.Property<int>("FileRoomAttachmentsRoomId")
                                                .HasColumnType("integer");

                                            b3.Property<string>("Bucket")
                                                .IsRequired()
                                                .HasColumnType("text");

                                            b3.Property<Guid>("Id")
                                                .HasColumnType("uuid");

                                            b3.HasKey("FileRoomAttachmentsRoomId")
                                                .HasName("pk_rooms");

                                            b3.ToTable("rooms");

                                            b3.ToJson("attachments");

                                            b3.WithOwner()
                                                .HasForeignKey("FileRoomAttachmentsRoomId")
                                                .HasConstraintName("fk_rooms_rooms_file_room_attachments_room_id");
                                        });

                                    b2.Navigation("Location")
                                        .IsRequired();
                                });

                            b1.Navigation("PdfRoomScheme");

                            b1.Navigation("Photo");
                        });

                    b.OwnsOne("Domain.Models.Room.RoomScheduleAddress", "ScheduleAddress", b1 =>
                        {
                            b1.Property<int>("RoomId")
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            b1.Property<string>("Address")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("schedule_address_address");

                            b1.Property<string>("RoomNumber")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("schedule_address_room_number");

                            b1.HasKey("RoomId");

                            b1.ToTable("rooms");

                            b1.WithOwner()
                                .HasForeignKey("RoomId")
                                .HasConstraintName("fk_rooms_rooms_id");
                        });

                    b.Navigation("Attachments")
                        .IsRequired();

                    b.Navigation("FixInfo")
                        .IsRequired();

                    b.Navigation("Parameters")
                        .IsRequired();

                    b.Navigation("ScheduleAddress");
                });
#pragma warning restore 612, 618
        }
    }
}
